CREATE TABLE PRODUCT (
ID NUMBER(7) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR2(255) NOT NULL,
PRICE DECIMAL(10,2) NOT NULL,
PRODUCT_TYPE NUMBER(1) NOT NULL,
IS_IMPORTED CHAR(1) DEFAULT 'N' NOT NULL
);

INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('BOOK',12.49,1,'N');
INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('CD MUSIC',14.99,4,'N');
INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('CHOCOLATE BAR',0.85,2,'N');
INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('BOX OF CHOCOLATE',10.50,2,'S');
INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('BOTTLE OF PERFUME',47.50,4,'S');
INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('BOTTLE OF PERFUME',27.99,4,'S');
INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('BOTTLE OF PERFUME',18.99,4,'N');
INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('PACKET OF HEADACHE PILLS',9.75,1,'N');
INSERT INTO PRODUCT(NAME, PRICE, PRODUCT_TYPE, IS_IMPORTED)
VALUES('BOX OF CHOCOLATE',11.25,2,'S');